build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=codecoverage'
                coverage:
                    file: 'codecoverage'
                    format: 'php-clover'
